when:
  - event:
    - tag
    - manual
    
steps:
  - name: build
    image: gradle:jdk21-corretto-alpine
    commands:
      - gradle build
      - mkdir -p /crow/build
      - cp ./build/libs/vivecraftcompat-1.21-$CI_COMMIT_TAG.jar /crow/build/

  - name: release
    depends_on:
      - build
    image: woodpeckerci/plugin-release
    settings:
      api-key:
        from_secret: github-release-key
      files:
        - /crow/build/*.jar

