when:
  - event:
    - tag
    - manual

steps:
  - name: build
    image: gradle:jdk21-corretto
    environment:
      GRADLE_USER_HOME: /crow/gradle
    commands:
      - mkdir -p /crow/gradle
      - gradle build -s
      - mkdir -p /crow/build
      - cp ./build/libs/vivecraftcompat-1.21-$CI_COMMIT_TAG.jar /crow/build/

  - name: release
    depends_on:
      - build
    image: codeberg.org/woodpecker-plugins/release:latest
    settings:
      title: $CI_COMMIT_TAG
      api-key:
        from_secret: github-release-key
      files:
        - /crow/build/*.jar

